# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rust_wrappers", use_symbols = TRUE, package_name = "rust")

#' @docType package
#' @usage NULL
#' @useDynLib rust, .registration = TRUE
NULL

#' Do value iteration for GridWorld
#' @export
value_iteration <- function(reward, end_cell) .Call(wrap__value_iteration, reward, end_cell)

